### ISSUE TITLE
IndexError: list index out of range -- what does this mean?

### ISSUE THREAD

**Issue by adamwritescode** [manwhoami/FindMyiPhone#11]
MacOS 10.13.3
Macbook Pro

```
Successfully authenticated
Sent location beacon to [3] devices
Awaiting response from iCloud...
Reprocessing iCloud response...
Traceback (most recent call last):
  File "FMIP copy2 - original.py", line 124, in <module>
    response = FMIP(username, password)
  File "FMIP copy2 - original.py", line 114, in FMIP
    return_string += "\033[91mStreet Address\033[0m: %s\n" % convert_coords(y["location"]["latitude"], y["location"]["longitude"])
  File "FMIP copy2 - original.py", line 18, in convert_coords
    formatted_address = json.loads(response.read())["results"][0]["formatted_address"]
IndexError: list index out of range

```

**Comment by stasyatr** [comment]
Same problem. It's error with method def convert_coords(lat, longitude). Possibly new version of API maps.google.com. Comment line 114 easy way to solve problem.
