### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by scorpius** [manwhoami/FindMyiPhone#5]
I've been getting this error lately. Does anyone else have this problem or is it something on my end?

```ruby
Traceback (most recent call last):
  File "../cloud/FindMyiPhone/FMIP.py", line 93, in <module>
    print FMIP(username, password),
  File "../cloud/FindMyiPhone/FMIP.py", line 46, in FMIP
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno -2] Name or service not known>
```

**Comment by manwhoami** [comment]
Apple made some changes to their backend recently. I updated the repo a few days ago with code adjustments to this change. I notice you're running an older version of the code based on the error at line 46. Update and let me know if that solves the issue 👍

**Comment by scorpius** [comment]
The update solves the problem. Thanks.
