### ISSUE TITLE
This no longer seems to be working. 

### ISSUE THREAD

**Issue by tomballgithub** [manwhoami/FindMyiPhone#8]
My scripts created with latest version back on Mar 29 stopped working recently.  Is there a fix available?

**Comment by tomballgithub** [comment]
```
Traceback (most recent call last):
  File "iphone4.py", line 127, in <module>
    response = FMIP(username, password)
  File "iphone4.py", line 83, in FMIP
    raise e
urllib2.HTTPError: HTTP Error 330:

```
